### ISSUE TITLE
No lines in model fit plots

### ISSUE THREAD

**Issue by ChlorisF** [JimGrange/flankr#3] opened 2022-07-19 20:33 UTC
Hi Jim,

I got a somewhat weird problem after running the model fit - when I tried to plot it, there were only dots (see figure below)... So I went back to check my data, and they seemed sensible. As my data actually contained multiple "conditions" (e.g., emotion type, Flanker image nationality, target image nationality), I tried to perform model fit using each condition, but the same problem remained.
<img src="https://user-images.githubusercontent.com/103331766/179837287-1c17f99b-1159-4860-b158-e76d62c9c6f3.png" width="500" />
Could you advise on potential reasons for (and solutions to) this? Many thanks!

Chloris
_Originally posted by @ChlorisF in https://github.com/JimGrange/flankr/issues/2#issuecomment-1189498494_

**Comment by JimGrange** [comment] 2022-07-20 07:27
Thanks Chloris, 

This issue might be caused by your response time being in milliseconds rather than seconds. If you divide your RT column by 1000 and try the fit again, that should work. If not, please let me know!

**Comment by JimGrange** [comment] 2022-07-28 12:17
Hi @ChlorisF - Just checking in whether the above solution worked for you.

**Comment by ChlorisF** [comment] 2022-07-31 15:43
> Thanks Chloris,
> 
> This issue might be caused by your response time being in milliseconds rather than seconds. If you divide your RT column by 1000 and try the fit again, that should work. If not, please let me know!

Hi @JimGrange, somehow my reply wasn't successfully sent although I crossed the item off my to-do list. I got tied up in a project until this weekend afterwards, hence the delay - many apologies!

The lines indeed appeared, thanks a lot! However, my model fit does not correspond to human data (Figure 1) even after I set the `parms` to be the "bestParameters" retrieved from the default model-fitting (Figure 2). The figures below used the DSTP model, but the same situation appeared for the SSP model. Should I find the "best" parameters in another way? Could you advise on how to do it? Let me know if I should open a new issue for this. Thanks a ton.

Figure 1. Fit of the DSTP model to my data (default setting)
<img src="https://user-images.githubusercontent.com/103331766/182034103-bd59be34-211f-4d9e-9c61-1a430078e408.png" width="500" />

Figure 2. Fit of the DSTP model to my data (using $bestParameters as parms)
<img src="https://user-images.githubusercontent.com/103331766/182034168-f90c250f-72ac-47bc-baab-fda82e0cc5ed.png" width="500" />

**Comment by JimGrange** [comment] 2022-07-31 18:39
Thanks @ChlorisF,

I will close this issue now. The poor fit of the model to your data isn't an issue with the package. I am not familiar with the data you are trying to model here, but I don't think either the DSTP nor the SSP model are appropriate here because of the following:

- Note for your CDFs for correct response time (left panel), your data shows slightly slower RTs for congruent responses than for incongruent responses for most quantiles. Both the DSTP model and the SSP model will always expect faster RTs for congruent response times.
- Also note that your CAF plot (right panel) shows decreasing accuracy with slower RTs for both congruent and incongruent trials. However, again both the DSTP and SSP model predict *better* accuracy at slower response times due to enhanced selectivity.

Is your data from a traditional flanker task, or are you trying to model some other paradigm?

**Closed as completed by JimGrange** 2022-07-31 18:39 UTC

**Comment by JimGrange** [comment] 2022-07-31 18:40
@ChlorisF Please feel free to email me if you want to chat about this further (grange [dot] jim [at] gmail [dot] com)
